// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6H8uEQlvQZV849EVXcTrJF6ypK42yPNk',
    appId: '1:835202296295:web:918fcbd90063e65143f542',
    messagingSenderId: '835202296295',
    projectId: 'instagram-1a3a6',
    authDomain: 'instagram-1a3a6.firebaseapp.com',
    storageBucket: 'instagram-1a3a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4E032E0cDjHR-nfJyoKDMsyDGbtIqM7U',
    appId: '1:835202296295:android:638d02030967ea9343f542',
    messagingSenderId: '835202296295',
    projectId: 'instagram-1a3a6',
    storageBucket: 'instagram-1a3a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5QNb7ttpSySbBYllBrL6zIexwDzto2Uo',
    appId: '1:835202296295:ios:bf4f38d4817b174143f542',
    messagingSenderId: '835202296295',
    projectId: 'instagram-1a3a6',
    storageBucket: 'instagram-1a3a6.appspot.com',
    iosBundleId: 'com.example.instagramClones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5QNb7ttpSySbBYllBrL6zIexwDzto2Uo',
    appId: '1:835202296295:ios:bf4f38d4817b174143f542',
    messagingSenderId: '835202296295',
    projectId: 'instagram-1a3a6',
    storageBucket: 'instagram-1a3a6.appspot.com',
    iosBundleId: 'com.example.instagramClones',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6H8uEQlvQZV849EVXcTrJF6ypK42yPNk',
    appId: '1:835202296295:web:2009526901b6946c43f542',
    messagingSenderId: '835202296295',
    projectId: 'instagram-1a3a6',
    authDomain: 'instagram-1a3a6.firebaseapp.com',
    storageBucket: 'instagram-1a3a6.appspot.com',
  );
}
